name: Run coin.py once

on:
  push:
    branches:
      - main  # Veya master, hangi dalda çalışmasını istiyorsanız
  workflow_dispatch: # Manuel tetikleme için de bu seçenek var

jobs:
  run-script:
    runs-on: ubuntu-latest  # İşlemi hangi ortamda çalıştıracağımız

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Kodu alır, yani repo'yu klonlar

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Python sürümünü belirtin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Eğer bağımlılıklar varsa requirements.txt dosyasına
          
      - name: Run coin.py
        run: |
          python coin.py  # coin.py dosyasını çalıştırır
